### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by zlatanvasovic** [tldr-pages/homebrew-tldr#1]
(Settings -> Danger Zone -> Archive this repository)

It's a Github-ish official way to show this repository is no longer active.

**Comment by zlatanvasovic** [comment]
This also prevents any further necro-ing the repository.

ping @sbrl

**Comment by sbrl** [comment]
Oh, wow. I didn't know this existed.

/cc @pxgamer and @agnivade to confirm

**Comment by owenvoke** [comment]
I think this seems fair enough to do. Make sure to close the issue first though. 👍 Otherwise you end up with any open issues being unclosable.
