### ISSUE TITLE
Error installing tldr: 'unistd.h' file not found

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/homebrew-tldr#1]
Installation log (curl dependency left out for brevity):
```
==> Installing tldr-pages/tldr/tldr
==> Downloading https://github.com/tldr-pages/tldr-cpp-client/archive/0.2.tar.gz
==> Downloading from https://codeload.github.com/tldr-pages/tldr-cpp-client/tar.gz/0.2
######################################################################## 100.0%
==> cd src && make
Last 15 lines from /Users/waldyrious/Library/Logs/Homebrew/tldr/01.cd:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:434:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:23:10:In file included from Helper.cpp:1:
In file included from ./Helper.h:1:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:434:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:23:10: fatal error: 'unistd.h' file not found
 fatal error: 'unistd.h' file not found
#include <unistd.h>
         ^
#include <unistd.h>
         ^
1 error generated.
make: *** [Helper.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
make: *** [tldr.o] Error 1
```

**Comment by Leandros** [comment]
Have you installed the command line tools in Xcode?

**Comment by waldyrious** [comment]
Ah, that was it, thanks. Perhaps the Readme could include `xcode-select --install` before the other commands, or at least mention that as a requirement.

**Comment by Leandros** [comment]
I just stumbled across this old ticket, we could create a bottled (binary) release for users, to not have Xcode installed.
However, how many people have brew, but no Xcode installed?

**Comment by waldyrious** [comment]
Well, I'm a newbie on OS X (using it for work only), and it happened to me (I wasn't the one setting up the machine). I guess a self-contained binary could make sense, but honestly a single command-line on the README seems like a simpler solution. Besides, compilation errors at least provide (hopefully) meaningful errors.

Or, we could do both :)

**Comment by Leandros** [comment]
I would rather not mention it in the readme, due to having Xcode correctly installed is necessary for all homebrew packages, but rather link to the official troubleshooting docs for homebrew (where your problem is mentioned). https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md


> compilation errors at least provide (hopefully) meaningful errors.

You obviously have never worked with either templates in C++ or GCC (or, shudder, both at the same time). :grin:

**Comment by Leandros** [comment]
I've added a troubleshooting section to the readme: https://github.com/tldr-pages/homebrew-tldr#troubleshooting

**Comment by waldyrious** [comment]
:+1: but shouldn't the homebrew-tldr repo be linked from the tldr-cpp-client readme, in the appropriate section?

And yes, I'm aware compile errors can be rather obscure (I've been bitten by some myself), but at least they have the potential to be more informative than runtime errors :)
