### ISSUE TITLE
Should not default to colors that don't work with Terminal.app colors

### ISSUE THREAD

**Issue by garysweaver** [tldr-pages/homebrew-tldr#2]
In OS X, some Terminal.app themes ("Profiles") don't work well with the default color scheme, e.g.

![too_hard_to_read](https://cloud.githubusercontent.com/assets/92330/12025932/a2b54614-ad81-11e5-8cdf-c918888bc454.png)

**Comment by notpeter** [comment]
You should file this issue against [tldr-pages/tldr-cpp-client](https://github.com/tldr-pages/tldr-cpp-client/) which is the underlying tldr client this tap installs.

**Comment by Leandros** [comment]
Even better, I'll close this issue, due to being fixed. https://github.com/tldr-pages/tldr-cpp-client/pull/6

**Comment by garysweaver** [comment]
Looks great now! Thanks!!

![screen shot 2016-01-13 at 10 28 14 am](https://cloud.githubusercontent.com/assets/92330/12298519/7b7feafc-b9e0-11e5-93c6-486cad1e6060.png)
