### ISSUE TITLE
Add this to standard Homebrew

### ISSUE THREAD

**Issue by danielcompton** [tldr-pages/homebrew-tldr#6]
Would it be possible to move this formula into Homebrew proper so people don't need to tap it, and they can find it with `brew search tldr`?

**Comment by Leandros** [comment]
Sure, feel free to submit it to the homebrew guys. I remember trying to do it a few years back, but I was rejected due to `tldr` having to few users.

I suspect I would get the same response today, unfortunately.

**Comment by danielcompton** [comment]
I've opened https://github.com/Homebrew/homebrew-core/pull/4637, we'll see how we go.
